// <auto-generated />
namespace SoftUniAutomapperEcercises.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class oneToManySelf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(oneToManySelf));
        
        string IMigrationMetadata.Id
        {
            get { return "201703281947537_oneToManySelf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
